// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const DEFAULT_CONFIG: typeof import('/Users/xukeek/Develop/ext/translate-simple/utils/storage').DEFAULT_CONFIG
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const TranslationCache: typeof import('/Users/xukeek/Develop/ext/translate-simple/utils/cache').TranslationCache
  const browser: typeof import('wxt/browser').browser
  const collectTextBlocks: typeof import('/Users/xukeek/Develop/ext/translate-simple/utils/dom').collectTextBlocks
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const getConfig: typeof import('/Users/xukeek/Develop/ext/translate-simple/utils/storage').getConfig
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const injectStyles: typeof import('/Users/xukeek/Develop/ext/translate-simple/utils/dom').injectStyles
  const removeTranslations: typeof import('/Users/xukeek/Develop/ext/translate-simple/utils/dom').removeTranslations
  const renderTranslation: typeof import('/Users/xukeek/Develop/ext/translate-simple/utils/dom').renderTranslation
  const setConfig: typeof import('/Users/xukeek/Develop/ext/translate-simple/utils/storage').setConfig
  const storage: typeof import('wxt/utils/storage').storage
  const updateConfig: typeof import('/Users/xukeek/Develop/ext/translate-simple/utils/storage').updateConfig
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { TranslationCache } from '/Users/xukeek/Develop/ext/translate-simple/utils/cache'
  import('/Users/xukeek/Develop/ext/translate-simple/utils/cache')
  // @ts-ignore
  export type { TextBlock } from '/Users/xukeek/Develop/ext/translate-simple/utils/dom'
  import('/Users/xukeek/Develop/ext/translate-simple/utils/dom')
}
